#!/bin/sh -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 root file"
    exit 1
fi

ROOT=$1
FILE=$2
DEPS=$(sed -n 's/^`include "\(.*\.v\)"$/\1/p' $FILE | tr '\n' ' ')

if [ -z "$DEPS" ]; then
    exit
fi

echo "$ROOT: $DEPS"

for DEP in $DEPS; do
    $0 $ROOT $DEP
done
